# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=600, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
