# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-04 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_auto_20171104_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
    ]
